<a href="https://colab.research.google.com/github/Ibravrca-18/PEMROSESANBAHASAALAMI/blob/main/UTSNLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

In [23]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [24]:
from google.colab import files
uploaded = files.upload()

Saving genap.csv to genap (1).csv

In [25]:
import pandas as pd
import re
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [26]:
df = pd.read_csv('genap.csv', sep=';')
df.head()

    No                                               Data
0  1.0  KOMPAS.com – Banjir dan longsor yang melanda A...
1  NaN                                                NaN
2  NaN  Sumber: https://lestari.kompas.com/read/2026/0...
3  NaN                                                NaN
4  NaN                                                NaN

In [27]:
texts = df['Data'].str.lower()

In [28]:
texts.head()

0    kompas.com – banjir dan longsor yang melanda a...
1                                                  NaN
2    sumber: https://lestari.kompas.com/read/2026/0...
3                                                  NaN
4                                                  NaN
Name: Data, dtype: object

In [29]:
# TEKS CLEANING #
def cleaning(text):
    text = re.sub(r'http\S+', '', str(text))  # hapus URL
    text = re.sub(r'[^a-zA-Z\s]', '', text)   # hapus simbol & angka
    return text

texts = texts.apply(cleaning)

In [30]:
#TOKENIZATION
texts = texts.apply(lambda x: x.split())

In [31]:
# NORMALIZATION
slang_dict = {
    "gk": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "bgt": "banget",
    "yg": "yang",
    "dr": "dari"
}

def normalize(tokens):
    return [slang_dict[word] if word in slang_dict else word for word in tokens]

texts = texts.apply(normalize)

In [32]:
# Stopword Removal
factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stopwords]

texts = texts.apply(remove_stopwords)

In [33]:
# Stemming
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

texts = texts.apply(stemming)

In [34]:
# =========================
# LEMMATIZATION
# =========================
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

texts = texts.apply(lemmatization)

In [35]:
# Penggabungan Hasil Proses
df['processed_text'] = texts.apply(lambda x: ' '.join(x))
df.head()

,No,Data,processed_text
0,1.0,KOMPAS.com – Banjir dan longsor yang melanda A...,kompascom banjir longsor landa aceh akhir ting...
1,NaN,NaN,nan
2,NaN,Sumber: https://lestari.kompas.com/read/2026/0...,sumber
3,NaN,NaN,nan
4,NaN,NaN,nan

In [36]:
# Tampilan sebelum dan sesudah di peroses
df[['Data', 'processed_text']].head(10)

,Data,processed_text
0,KOMPAS.com – Banjir dan longsor yang melanda A...,kompascom banjir longsor landa aceh akhir ting...
1,NaN,nan
2,Sumber: https://lestari.kompas.com/read/2026/0...,sumber
3,NaN,nan
4,NaN,nan
5,Membership: https://kmp.im/plus6,membership
6,Download aplikasi: https://kmp.im/app6,download aplikasi